"""update task cascade delete

Revision ID: 44d0bd7a1ed9
Revises: da11398c851e
Create Date: 2023-11-25 13:23:35.530950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d0bd7a1ed9'
down_revision: Union[str, None] = 'da11398c851e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_column_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'columns', ['column_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_column_id_fkey', 'tasks', 'columns', ['column_id'], ['id'])
    # ### end Alembic commands ###
