"""added task color

Revision ID: 9169d471b013
Revises: 44d0bd7a1ed9
Create Date: 2023-11-25 17:41:40.909862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9169d471b013'
down_revision: Union[str, None] = '44d0bd7a1ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('color', sa.VARCHAR(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'color')
    # ### end Alembic commands ###
