from enum import Enum


class Permission(Enum):
    GET_COLUMN = "GET_COLUMN"
    CREATE_COLUMN = "CREATE_COLUMN"
    UPDATE_COLUMN = "UPDATE_COLUMN"
    DELETE_COLUMN = "DELETE_COLUMN"

    GET_TASK = "GET_TASK"
    CREATE_TASK = "CREATE_TASK"
    UPDATE_TASK = "UPDATE_TASK"
    DELETE_TASK = "DELETE_TASK"
